name: On Push Run

on: push

env:
  DEVOPS_DIR: python-to-elastic
  ES_INDEX: test-auto

jobs:
  process_files:
    name: Process Files
    runs-on: ubuntu-latest
    steps:
    - name: checkout of last commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35

    - name: check-out python to elastic repository
      uses: actions/checkout@v3
      with:
        repository: WalterPaixaoCortes/python-to-elastic
        ref: main
        token: ${{ secrets.GH_PAT }}
        path: ${{ env.DEVOPS_DIR }}

    - name: copy changed files to devops
      run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            cp $file ${{ env.DEVOPS_DIR }}/excel/
          done
      shell: sh

    - name: install requirements
      run: |
           cd ${{ env.DEVOPS_DIR }} 
           pip install -r requirements.txt
      shell: sh

    - name: run convert script
      run: |
           cd ${{ env.DEVOPS_DIR }}
           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
             python excel_to_es_json.py --no-geocode -file excel/$file
           done
      shell: sh

    - name: clean data
      run: |
           cd ${{ env.DEVOPS_DIR }}
           for jsonfile in json/*.json ; do
              python clean_data.py -file json/$jsonfile -index ${{ ES_INDEX }}
           done 
      shell: sh
